// Generated by CoffeeScript 1.3.3
var app, connect, fs, router;

connect = require('connect');

router = require('route66');

fs = require('fs');

router.get('/', function(req, res) {
  return fs.readFile("" + __dirname + "/index.html", function(err, source) {
    return res.end(source.toString());
  });
});

router.post('/', function(req, res) {
  res.writeHead(301, {
    Location: '/post'
  });
  return res.end();
});

router.get('/post', function(req, res) {
  return fs.readFile("" + __dirname + "/post.html", function(err, source) {
    return res.end(source.toString());
  });
});

router.get('/sub', function(req, res) {
  return fs.readFile("" + __dirname + "/sub.html", function(err, source) {
    return res.end(source.toString());
  });
});

app = connect();

app.use(connect["static"]("" + __dirname + "/../dist"));

app.use(connect["static"]("" + __dirname + "/../libs"));

app.use(router);

app.listen(3000);
